### ISSUE TITLE
"app/assets/javascripts/concerto_weather/weather.js" not loaded in the page

### ISSUE THREAD

**Issue by maxencefrenette** [concerto/concerto-weather#22]
The javascript file app/assets/javascripts/concerto_weather/weather.js doesn't seem to be loaded when trying to add new weather content. I was able to make everything work by copy-pasting the contents of the file in chrome's javascript console.

**Comment by mfrederickson** [comment]
@maxencefrenette we're not seeing this problem in our testing.  If you experience the same problem the next time you upgrade concerto or the weather plugin, please reopen another ticket.  

Please note that you wont typically see the individual javascript assets loaded in the browser because they are concatenated and minified and given a unique name (such as `http://concerto/assets/concerto_weather/application-94a154e7f7f7900c5ea2dd2618affa04.js`).
